/**
 * Give a face to every team, team member and staff account that lacks one.
 *
 *   npm run backfill-avatars           # apply
 *   npm run backfill-avatars -- --dry  # report only
 *
 * Avatars arrived after some of this data did, and until now they were only
 * generated by the roster and avatar-picker routes — so a team created and left
 * alone kept `avatar: null` forever and the console fell back to initials.
 * `POST /teams` and `POST /users` now generate one at creation; this catches
 * everything written before that.
 *
 * Idempotent: a record that already has an avatar is left exactly as it is,
 * including one an operator deliberately chose a different style for.
 *
 * `--restyle` additionally re-renders records whose avatar uses a style other
 * than the current default. Off by default, because overwriting a deliberate
 * choice is not a backfill.
 */
import mongoose from "mongoose";
import connectToDatabase from "../src/db/db";
import Team from "../src/models/teams";
import User from "../src/models/users";
import {
  DEFAULT_AVATAR_STYLE,
  DEFAULT_TEAM_AVATAR_STYLE,
  generateAndStoreAvatar,
} from "../src/services/avatars";

const dryRun = process.argv.includes("--dry");
const restyle = process.argv.includes("--restyle");

/**
 * Does this record need work?
 *
 * `expected` differs by kind: a TEAM defaults to abstract shapes and a PERSON
 * to a character, so that a team and a roster member are never rendered as the
 * same kind of thing in a list.
 */
const needsAvatar = (avatar: any, expected: string): boolean => {
  if (!avatar?.url) return true;
  return restyle && avatar.style !== expected;
};

async function main() {
  await connectToDatabase();

  let teams = 0;
  let members = 0;
  let users = 0;

  // ── Teams and their members ──────────────────────────────────────────
  for (const team of await Team.find({})) {
    let dirty = false;

    if (needsAvatar(team.avatar, DEFAULT_TEAM_AVATAR_STYLE)) {
      console.log(`  team    ${team.teamName}`);
      if (!dryRun) {
        team.avatar = (await generateAndStoreAvatar(
          DEFAULT_TEAM_AVATAR_STYLE,
          team.teamName
        ).catch(() => null)) as any;
      }
      teams++;
      dirty = true;
    }

    for (const m of team.members ?? []) {
      if (!needsAvatar((m as any).avatar, DEFAULT_AVATAR_STYLE)) continue;
      console.log(`  member  ${team.teamName} › ${(m as any).name}`);
      if (!dryRun) {
        (m as any).avatar = await generateAndStoreAvatar(
          DEFAULT_AVATAR_STYLE,
          String((m as any).name ?? team.teamName)
        ).catch(() => null);
      }
      members++;
      dirty = true;
    }

    if (dirty && !dryRun) await team.save();
  }

  // ── Staff accounts ───────────────────────────────────────────────────
  // Team-role users are excluded: they sign in by passkey and are represented
  // in every UI by their TEAM, which has its own avatar. Giving them a second,
  // different face would be a second identity for the same player.
  for (const user of await User.find({ role: { $ne: "team" } })) {
    if (!needsAvatar(user.avatar, DEFAULT_AVATAR_STYLE)) continue;
    const label = user.name ?? user.email ?? String(user._id);
    console.log(`  user    ${label}`);
    if (!dryRun) {
      user.avatar = (await generateAndStoreAvatar(
        DEFAULT_AVATAR_STYLE,
        String(label)
      ).catch(() => null)) as any;
      await user.save();
    }
    users++;
  }

  const total = teams + members + users;
  console.log(
    `\n${dryRun ? "Would give" : "Gave"} an avatar to ${total} record${total === 1 ? "" : "s"} ` +
      `(${teams} team${teams === 1 ? "" : "s"}, ${members} member${members === 1 ? "" : "s"}, ` +
      `${users} staff account${users === 1 ? "" : "s"}).`
  );
  if (total === 0) console.log("Everything already has a face.");

  await mongoose.connection.close();
}

main().catch(async (err) => {
  console.error(err?.message ?? err);
  await mongoose.connection.close().catch(() => undefined);
  process.exit(1);
});
